---
title: "ML in R"
author: "Jared P. Lander"
date: "6/25/2020"
output: 
    html_document:
        toc: true
        toc_float:
            smooth_scroll: true
            collapsed: false
        number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data

```{r}
piggyback::pb_download(file='data/med_costs.csv', repo='jaredlander/coursedata')
```

```{r}
here::here('data', 'med_costs.csv')
med <- readr::read_csv(here::here('data', 'med_costs.csv'))
```

```{r}
med
```

```{r}
library(ggplot2)
ggplot(med, aes(x=age, fill=sex)) + geom_histogram() + facet_wrap(~sex) + theme(legend.position='none')
ggplot(med, aes(x=age, y=charges, color=sex)) + 
    geom_point() + 
    geom_smooth() + 
    facet_wrap(~sex) + 
    theme(legend.position='none')

ggplot(med, aes(x=age, y=charges)) + 
    geom_point(aes(color=region)) + 
    geom_smooth() + 
    facet_wrap(~sex)

ggplot(med, aes(x=age, y=charges)) + 
    geom_point(aes(color=smoker)) + 
    geom_smooth() + 
    facet_wrap(~sex)
```

# Regression

$$
y \sim a + b_1x_1 + b_2x_2 + \cdots + b_px_p + \epsilon \\
\epsilon \sim N(0, \sigma)
$$

- Output: response, outcome, dependent variable, y, label, target
- Input: predictor, x, variable, covariate, feature, independent variable, data

## lm

```{r}
cost1 <- lm(charges ~ age + sex + smoker, data=med)
summary(cost1)
```

```{r}
library(coefplot)
coefplot(cost1, sort='magnitude')
coefplot(cost1, sort='magnitude', lwdInner=1.5, lwdOuter=0.5)
```

```{r}
cost2 <- lm(charges ~ scale(age) + sex + smoker, data=med)
coefplot(cost2, sort='magnitude')
```

```{r}
med
```

```{r}
2^6 - 1
2^10 - 1
2^25 - 1
2^120 - 1
```

## Lasso

$$
\hat{\beta} = argmin \left [ \sum (y_i - X_i\beta)^2 + \lambda \sum |\beta_j| \right ]
$$
```{r}
library(glmnet)
```

Is it pronounced "glmnet" or "g-l-m-net"?

glmnet is the winner

```{r eval=FALSE}
# this code is not run
# it would not work anyway
glmnet(y ~ x1 + x2, data=data)
```

Starting with glmnet 4.0 (possibly 3.0), you can use a formula

So we need to build our own matrices

Used to `useful::build.x()`

Now I use `{recipes}`

```{r}
library(recipes)

rec_glmnet1 <- recipe(charges ~ ., data=med) %>% 
    step_knnimpute(all_predictors()) %>% 
    # step_normalize(age, BMI) %>% 
    step_normalize(all_numeric(), -charges) %>%
    # step_center(all_numeric(), -charges) %>%
    # step_scale(all_numeric(), -charges, factor=2) %>%
    step_dummy(all_nominal(), one_hot=TRUE)
rec_glmnet1
```

```{r}
prepped_glmnet1 <- rec_glmnet1 %>% prep()
prepped_glmnet1
```

```{r}
prepped_glmnet1 %>% juice()
```

